### ISSUE TITLE
option to specify the coordinates length

### ISSUE THREAD

**Issue by franckl** [henrythasler/Leaflet.Geodesic#10]
It would be nice to be able to limit the coordinates length to save space, after 8 decimals it doesn't make much sense

**Comment by henrythasler** [comment]
Yeah, you're totally right. I'll check it.

**Comment by franckl** [comment]
Hi Henry, do you think this feature could be added in the next version ? 
thanks !

**Comment by henrythasler** [comment]
Leaflet stores all coordinates as numbers
(http://leafletjs.com/reference.html#latlng). Limiting the digits after
the the decimal point would not make any difference. There is only one
number type in JavaScript
(http://www.w3schools.com/jsref/jsref_obj_number.asp). I suggest we
leave it as it is right now.

**Comment by henrythasler** [comment]
No protest. Closed

**Comment by franckl** [comment]
Hi Henry,

Sorry for the delay. It was useful for me as I export the great circle as a
geoJSON file but it is fine

Best
