### ISSUE TITLE
Retain ‘alt’ values in Geodesic path

### ISSUE THREAD

**Issue by chrisveness** [henrythasler/Leaflet.Geodesic#100]
If a polyline is created from an array of LatLngs that includes `alt` fields, the `alt` values are included in the `Polyline.getLatLngs()` method.

However, if a geodesic is created from an array of LatLngs that includes `alt` fields, the `alt` values are lost in `Geodesic.getLatLngs()`.

For example, using the code:

![image](https://github.com/henrythasler/Leaflet.Geodesic/assets/1066395/fd4a347d-03a6-4b6c-b706-962d61ed0221)

I get results

![image](https://github.com/henrythasler/Leaflet.Geodesic/assets/1066395/f95b56c1-04eb-4aad-8b3e-51e821774350)

Would it be possible for the LatLngs in the geodesic matching the original supplied LatLngs (i.e. elements 0, 4, 8) to retain the `alt` value?

**Comment by henrythasler** [comment]
Thanks for sharing. I will investigate what is needed to fix this.

**Comment by henrythasler** [comment]
I applied a fix that with

```
        const path = [
            new L.LatLng(50, 30, 10),
            new L.LatLng(51, 31, 20),
            new L.LatLng(52, 32, 30),
        ];

        const polyline = L.polyline(path);
        console.log("polyline", polyline.getLatLngs());

        const geodesic = L.geodesic(path, { steps: 1 });
        console.log("geodesic", geodesic.getLatLngs());
```
results in

```
polyline 
Array(3) [ {…}, {…}, {…} ]
​0: Object { lat: 50, lng: 30, alt: 10 }
​1: Object { lat: 51, lng: 31, alt: 20 }
​2: Object { lat: 52, lng: 32, alt: 30 }
​length: 3
​
geodesic 
Array [ (9) […] ]
​0: Array(9) [ {…}, {…}, {…}, … ]
​​0: Object { lat: 50, lng: 30, alt: 10 }
​​1: Object { lat: 50.25079782556117, lng: 30.24605278261522 }
​​2: Object { lat: 50.50107067883589, lng: 30.494706597056435 }
​​3: Object { lat: 50.7508082524969, lng: 30.74600690008849 }
​​4: Object { lat: 51, lng: 31, alt: 20 }
​​5: Object { lat: 51.25079180200066, lng: 31.245910001380075 }
​​6: Object { lat: 51.5010627538586, lng: 31.494514272540606 }
​​7: Object { lat: 51.75080239136747, lng: 31.745861171537758 }
​​8: Object { lat: 52, lng: 32, alt: 30 }
​​length: 9
```

Please note that you need to provide `L.LatLng`-Objects for now. If this is ok for now I will create a release. 

Support for Literals (as in your example) requires an additional patch in the Leaflet-typings that I will check out next.

**Comment by chrisveness** [comment]
That's great, thank you. I can use `LatLng`  objects in place of literals.

**Comment by henrythasler** [comment]
[v2.7.0](https://github.com/henrythasler/Leaflet.Geodesic/releases/tag/v2.7.0) is now released.
