### ISSUE TITLE
Geodesic limited to -180,180 lon

### ISSUE THREAD

**Issue by ilblog** [henrythasler/Leaflet.Geodesic#11]
Hi

It seems to me that Geodesic does not support lines, that cross date line. Otherways great pluging, I am happy for it.

![screen shot 2015-06-05 at 09 36 40](https://cloud.githubusercontent.com/assets/7228326/8001497/aa588ace-0b66-11e5-80dc-fb857bb71315.png)

**Comment by henrythasler** [comment]
Actually, you can do that. It's an experimental feature. You have to set the Option 'wrap' to false. I have created a new example to demonstrate how to use it:
[Interactive Demo (noWrap)](http://www.thasler.com/leaflet.geodesic/example/interactive-noWrap.html)
