### ISSUE TITLE
How can I change the icons

### ISSUE THREAD

**Issue by hmarina** [henrythasler/Leaflet.Geodesic#12]
Hello every one, I tried to change the icons but doesnt work, Is there a way to change the two icons.
I do this.

var icon1 = L.Icon.extend({
    options: {
        shadowUrl: 'myicon1.png',
        iconSize:     [38, 95],
        shadowSize:   [50, 64],
        iconAnchor:   [22, 94],
        shadowAnchor: [4, 62],
        popupAnchor:  [-3, -76]
    }
});

var icon2 = L.Icon.extend({
    options: {
        shadowUrl: 'myicon2.png',
        iconSize:     [38, 95],
        shadowSize:   [50, 64],
        iconAnchor:   [22, 94],
        shadowAnchor: [4, 62],
        popupAnchor:  [-3, -76]
    }
});

var A = L.marker(punto1, {draggable: false}, {icon: icon1}).addTo(map);
var B = L.marker(punto2, {draggable: false}, {icon: icon2}).addTo(map);

**Comment by henrythasler** [comment]
You need to do this as follows:
```JavaScript
var myIcon = L.icon({
    iconUrl:
'http://icons.iconarchive.com/icons/blackvariant/button-ui-requests-15/48/Filehippo-icon.png',
    iconSize: [48, 48],
    iconAnchor: [24, 24],
    popupAnchor: [0, -28],
});

var B = L.marker(berlin, {draggable: true, icon:
myIcon}).addTo(map).bindPopup("Drag me.").openPopup();
```
full example: http://jsfiddle.net/h1r3yagb/
refer to: http://leafletjs.com/reference.html#icon

**Comment by hmarina** [comment]
Thank you so much
