### ISSUE TITLE
Define a geodesic line using 3 points.

### ISSUE THREAD

**Issue by ryantheleach** [henrythasler/Leaflet.Geodesic#17]
I want to define a great circle arc using 3 user specified points using leaflet. So first click starts it, second click  limits to 1 great circle, 3rd click is used to cut the great circle at the point clicked. 
![image](https://cloud.githubusercontent.com/assets/141554/11644563/078827fe-9d9d-11e5-940a-659a56b242b4.png)

Is this possible using this library?

**Comment by henrythasler** [comment]
Trying do define an arc like that doesn't get you an unambiguous figure.
You need at least 3 points on the arc or the center and 2 points on the arc.
After that you need to modify the loop
'''
   for(s=1; s<=this.options.steps; )  
'''
in the function
'''
   createCircle: function (center, radius)
'''
and this line as well
'''
    direct = this._vincenty_direct(L.latLng(center),
360/this.options.steps*s, radius, this.options.wrap);
'''
to draw only a part of the circle.

I can't give you any details w/o trying but let me know how far you get.
Maybe I can help you further.

**Comment by ryantheleach** [comment]
I don't understand. In 2d space you would be correct, but considering that this is a great circle which is the circle create by slicing the earth in 2 hemispheres, isn't there only 1 possible great circle for 2 points(assuming that it isn't a pair of antipodal points(I'm happy just cancelling the user interaction for that exact case as the result is handled by a system I don't control)? The rest is just how you define the beginning and ending of the arc? (which to start with would be the shorter of the 2 arcs, until the third point is defined)

**Comment by henrythasler** [comment]
If you want the arc to be a part of a great circle you just define two
points. That's what Leaflet.Geodesic is about. It will handle the rest.
If you need a circle (not a great circle) the earth is just a surface.
2d space if you would, because the circle can't leave the surface. 
Otherwise you need to explain in detail what you are trying to do.

**Comment by ryantheleach** [comment]
> If you want the arc to be a part of a great circle you just define two points. 

Sure, but say if I wanted to keep the arc the same great circle, but extend the ends?


https://gyazo.com/74425f9ec9afb1368814b6432017efa4 Shows a gif of my first attempt, however this uses 2d lines and doesn't convert to geodesic lines correctly, so causes small errors.
