### ISSUE TITLE
Polyline v/s MultiPolyline

### ISSUE THREAD

**Issue by bhaskarvk** [henrythasler/Leaflet.Geodesic#22]
I'm using the Legacy branch w/ Leaflet 0.7.7.
I see that in 12e5f46 the L.Geodesic was changed to extend from Polyline instead of MultiPolyline.
But the documentation still says we need to pass an `LatLng[] []` which is required for MultiPolyline and Polyline just takes `LatLng[]`.

So I tried passing just `LatLng[]` but that just gives a straight line like a normal Polyline would.
So then I tried passing `LatLng[][]` as the README mentions, but that results in a Javascript error as L.Polyline is not initialized correctly.

So then I changed the plugin code back again to extend from MultiPolyline and then it works correctly when passing `LatLng[][]`.

**Comment by henrythasler** [comment]
Maybe some check-in issue while changing branches and tags. Will check that soon.
