### ISSUE TITLE
Custom Projection support

### ISSUE THREAD

**Issue by bhaskarvk** [henrythasler/Leaflet.Geodesic#23]
In the code I see the default datum set to WSG84. Could this plugin be modified to support a custom projection supplied using the crs option of the map. I'm using Proj4Leaflet to supply custom projections, and was wondering if this plugin could support them.

**Comment by henrythasler** [comment]
I have no experience with other projections and leaflet. Have you tried it? It may work if Leaflet does the reprojection of any objects added to the map. Let me know the results.

**Comment by bhaskarvk** [comment]
It does work with Custom Projections. Awesome!!

![Imgur](http://i.imgur.com/fVXVRJI.png)
