### ISSUE TITLE
Can I use this code in R?

### ISSUE THREAD

**Issue by aditya-kothari** [henrythasler/Leaflet.Geodesic#24]
Hi Henry,

Can use the interactive.html code in leaflet R? If so, how do I do it?

Thanks for your time!
Aditya

**Comment by henrythasler** [comment]
I have never used R so I don't know. But let me and others know if it works.

**Comment by bhaskarvk** [comment]
@aditya-kothari I have integrated this plugin in my [leaflet.extras](https://github.com/bhaskarvk/leaflet.extras) package. You can see an example @ rpubs.com/bhaskarvk/geodesic.

@henrythasler You can close this issue :)

**Comment by henrythasler** [comment]
Thanks for sharing!
