### ISSUE TITLE
Failed to minify with create-react-app

### ISSUE THREAD

**Issue by stephenhandley** [henrythasler/Leaflet.Geodesic#31]
When using Leaflet.Geodesic as a dependency in a `create-react-app` application, I am seeing the following error:
```
Failed to minify
./node_modules/Leaflet.Geodesic/Leaflet.Geodesic.js:70 
```

Could you please publish an es5 compatible version as described here?
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

you could use webpack/babel to generate the code, but it doesn't look like you're using much non-es5 code and so it may just be a matter of replacing all `let` and `const` usage with `var`.

**Comment by henrythasler** [comment]
I just created an es5-branch. It also includes a minified version. Please check that out.

**Comment by stephenhandley** [comment]
awesome thanks! will check it out.

**Comment by Azmisov** [comment]
I've tested this out and it is working.

**Comment by henrythasler** [comment]
Thanks for the feedback

**Comment by stephenhandley** [comment]
Thanks @henrythasler and @Azmisov

**Comment by cknakua** [comment]
@henrythasler When do you plan on merging ~Leaflet.Geodesic/pull/34 to ES5?

**Comment by henrythasler** [comment]
@cknakua I'm currently not inclined to support ES5 unless absolutely necessary.
