### ISSUE TITLE
JS fiddle broken

### ISSUE THREAD

**Issue by bmcgary** [henrythasler/Leaflet.Geodesic#33]
The fiddle for this question:
> Q: I want to draw only part (eg. halfway) of a geodesic line between two places?
> see http://jsfiddle.net/h1r3yagb/2

is broken. Looks like some hosting dependencies are missing.
(I was able to hack it together by pasting in the missing deps into the html as a script tag to see if this lib would work for what I needed. Works great! This lib does exactly what I need! Thank you!)

**Comment by henrythasler** [comment]
Thanks for the hint.
Fixed: see http://jsfiddle.net/h1r3yagb/20/
