### ISSUE TITLE
Script does not work with IE

### ISSUE THREAD

**Issue by samipuro** [henrythasler/Leaflet.Geodesic#38]
Latest (and previous to latest) script revision throw errors with latest Internet Explorer (Win 10) and apparently also iPad/Safari. ==> Does not load/work.
_Line: 46
Error: Object doesn't support property or method 'geodesic'_

Also if you try to minimize the script for example with https://javascript-minifier.com/ you will get 
_// Error : Unexpected token: name (obj)
// Line  : 68
// Col   : 8_

Chrome & Firefox OK.
![clipboard01](https://user-images.githubusercontent.com/36813566/36952106-2de5ef20-2014-11e8-9d45-2f59f2d33a18.jpg)

**Comment by henrythasler** [comment]
Leaflet.geodesic uses some ESE6-Features that are not supported by IE11. See https://kangax.github.io/compat-table/es6/#ie11
I recommend to use Edge, Chrome or Firefox

**Comment by henrythasler** [comment]
If you are stuck with IE11 or need to minify code, please see the dedicated ES5-branch: https://github.com/henrythasler/Leaflet.Geodesic/tree/es5
