### ISSUE TITLE
addLatLng() doesn't draw a Great Circle

### ISSUE THREAD

**Issue by elmatou** [henrythasler/Leaflet.Geodesic#51]
Using `addLatLng()` on a `Geodesic` do not draw a great circle but a straight line instead.

the method is inherited from `Polyline` but has not been patched to draw a polyline.

**Comment by henrythasler** [comment]
Yes, I will re-implement this method for use with geodesic lines.

**Comment by henrythasler** [comment]
Depends on: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40505

**Comment by henrythasler** [comment]
closed with v2.5.0
Let me know if that works for you.
