### ISSUE TITLE
Accces properties of a Geodesic.

### ISSUE THREAD

**Issue by elmatou** [henrythasler/Leaflet.Geodesic#52]
Hi,

I need some information about a Great Circle drawn with `Geodesic`, in particular the initial and final bearings, the coordonate of a midpoint, but I do not get how to access the properties. is it through the `geom` object ?

**Comment by henrythasler** [comment]
It can be done like this:
```
var berlin = new L.LatLng(52.5, 13.35);
var losangeles = new L.LatLng(33.82, -118.38);
const geo = L.geodesic();
console.log(geo.geom.geodesic.inverse(berlin, losangeles))
console.log(geo.geom.geodesic.midpoint(berlin, losangeles))
```
The result is:
```
Object { distance: 9360165.784493221, initialBearing: 321.4761390184605, finalBearing: 207.18572716613716 }
Object { lat: 65.24359311042674, lng: -71.51008528822054 }
```

**Comment by elmatou** [comment]
Thx for your answer. 
That what I found, but I wandered if there is an access to the actual info of the current Geodesic object.

Anyhow if this part of the API will be preserved, I'm gonna go with it.
