### ISSUE TITLE
Installation via npm, the project folder does not contain code

### ISSUE THREAD

**Issue by binarikateam** [henrythasler/Leaflet.Geodesic#57]
![image](https://user-images.githubusercontent.com/13253376/71066875-9e181700-2184-11ea-99bb-c6b8a20eca22.png)

After installation, src and dst directories were not found

**Comment by henrythasler** [comment]
I just tried it (`npm i leaflet.geodesic`) in a blank folder and found no issues. All files in the dist-folder were installed. My npm version is 6.11.3.

**Comment by binarikateam** [comment]
Hello, tnx for answer, my npm -v is 6.13.0.
I also run
`npm i leaflet.geodesic`
and get this
```
+ leaflet.geodesic@2.5.2
added 2 packages from 1 contributor and audited 41862 packages in 14.431s
```
![image](https://user-images.githubusercontent.com/13253376/71162787-e440a980-225c-11ea-8ec9-21028d37636f.png)

**Comment by binarikateam** [comment]
Sorry for that, clearing the cache helped
`npm cache clean --force`
![image](https://user-images.githubusercontent.com/13253376/71163097-75178500-225d-11ea-9ea3-40beda1fba1e.png)

**Comment by henrythasler** [comment]
:-)
