### ISSUE TITLE
Extract calculations into a separate library

### ISSUE THREAD

**Issue by zakjan** [henrythasler/Leaflet.Geodesic#64]
Hi @henrythasler, would it be possible to extract the geodesic calculations into a separate library? I'm going to implement a similar drawing library for Mapbox. Sharing this part of code would be a great help!

**Comment by henrythasler** [comment]
Well, as I have just taken the functions I need from [chrisveness/geodesy](https://github.com/chrisveness/geodesy) it may be reasonable to use that library instead?

**Comment by zakjan** [comment]
Ok, thanks, I'll check it! I'm wondering what is the reason why you haven't used it as dependency, and copied it instead? Maybe some Leaflet-specific workarounds?

**Comment by henrythasler** [comment]
I only need a few functions from that lib so I think it's not worth having an additional dependency for that.
