### ISSUE TITLE
Leafletjs 1.7.1

### ISSUE THREAD

**Issue by Daniboi737** [henrythasler/Leaflet.Geodesic#68]
Hello! I have been trying to use this with Leafletjs 1.7.1, I Updated from 1.3.3 so does this just mean this don’t work on higher versions on Leaflet?

**Comment by henrythasler** [comment]
Can you give some details what is not working as expected. I will check as soon as possible.

**Comment by henrythasler** [comment]
I just checked with leaflet 1.7.1 and it works just fine.

**Comment by Daniboi737** [comment]
Sorry for late response. What happens with me is that I have markers on a map. When I hover or Click on a mobile device, it display the geodesic lines, but when I changed the Leaflet version the lines stopped displaying. But I changed the version back and works now, just wondering on this when I might need to update the version. Thank you

**Comment by henrythasler** [comment]
Can you be a bit more specific and maybe share the code or create a simple example that shows this behavior. Also: are there any console logs that may help?
