### ISSUE TITLE
Bearing

### ISSUE THREAD

**Issue by briandoylegit** [henrythasler/Leaflet.Geodesic#69]
Hi Henry,

I don't suppose you might create an example with Initial Bearing output combined with Final Bearing.
i.e. An info box with Initial Bearing xxx.xxx Final Bearing xxx.xxx
It would be most helpful for me.

Many thanks

Brian

**Comment by henrythasler** [comment]
You can calculate this info with some internal methods like this:
```
const Berlin = {lat: 52.5, lng: 13.35};
const LosAngeles = {lat: 33.82, lng: -118.38};
const line = new L.Geodesic();

extendedStats = line.geom.geodesic.inverse(Berlin, LosAngeles)
console.log(`initialBearing=${extendedStats.initialBearing} finalBearing=${extendedStats.finalBearing}`)
```
Here is a live example: https://jsitor.com/tkp4TOqNU7

**Comment by briandoylegit** [comment]
Hi Henry,

Many thanks for Leaflet.Geodesic and this example.
Exactly what I need.

Happy Christmas

Brian
