### ISSUE TITLE
required build artefacts

### ISSUE THREAD

**Issue by henrythasler** [henrythasler/Leaflet.Geodesic#82]
The build pipeline currently generates these files:
![image](https://user-images.githubusercontent.com/6277203/148369438-25e8abab-7880-4cec-8abe-975acdb1cb1f.png)

The CDN statistics show that almost all downloads are just the `umd.min.js`-file:
![image](https://user-images.githubusercontent.com/6277203/148369620-1218fd9d-cf0e-45ec-85ea-1e9bcd32148b.png)

**Questions:** 
1. Do I need to continue to provide the other (esm, non-minified) files? Let me know your opinion.
2. How can I properly test these generated files?

**Comment by matafokka** [comment]
> Do I need to continue to provide the other (esm, non-minified) files? Let me know your opinion.

I'd suggest keeping everything as it is. Who knows what might come in handy?

By the way, it'd be great to add command like `build:debug` that'll build unminified UMD file for testing in browser. This will reduce compilation time. Caching also will help.

> How can I properly test these generated files?

You're not using any polyfills, browser-specific hacks or stuff like that. Basically, you get what you write, no need for other tests.

Jest should internally compile TS to JS, unless it uses deno, so your bundle is already tested.

**Comment by henrythasler** [comment]
Thanks for the feedback. I just cleaned up the build-scripts a bit (now platform independent) but left the resulting artifacts untouched. There is now also a `build:dev` command you could adapt for your purposes.

**Comment by matafokka** [comment]
Cool, thanks!
