### ISSUE TITLE
[question]  is there a way to show tooltips or labels crossing the anti meridian?

### ISSUE THREAD

**Issue by beebase** [henrythasler/Leaflet.Geodesic#89]
I tried binding tooltips like this but that doesn't work.
```
 const options = {
      radius: 1000 * 10,
      color: "red",
      fillOpacity: 1,
      fill: false,
      wrap: false,
    }
const marker = L.geodesiccircle(coord, options)
      .addTo(map)
      .on("click", onClickMarker)
    marker.bindTooltip(label, {
      permanent: true,
      direction: "top",
      interactive: true,
      offset: [0, 0],
    })
```

![image](https://user-images.githubusercontent.com/446089/178349748-d69821a1-02ef-409b-9a32-5f0003642a3a.png)

**Comment by henrythasler** [comment]
A geodesiccircle is just a polyline and I'm not sure if a tooltip here makes sense as it will not be centered to the circle automatically:
![image](https://user-images.githubusercontent.com/6277203/178543786-3d27d84f-d1c8-4913-b795-5cc3bc7f9bde.png)

I just tried with markers and it works just fine. The tooltip even moves when you move the circle.
![image](https://user-images.githubusercontent.com/6277203/178543255-1655e1d0-c5ab-4377-b92e-a5583adbc408.png)

Maybe use these instead of a circle?

**Comment by beebase** [comment]
Thanks for your answer. I tried it with plain markers but the result remains the same.
I managed to get it somewhat working by manipulating the marker coordinates (adding/substracting 360 lng.). 
As soon as distances exceed 180 degrees lng. , markers start to get confused. However, the geodesic lines are always perfectly generated.
The trick for markers is probably to always stay within -180 and +180 degrees lng. of the common departure point of all the lines.
I'm not too familiar with leaflet yet, but maybe I should try binding the markers together with the lines.
(ATM I'm generating markers and lines separately in different coord. array loops, which I should optimise into one loop anyway.

Any tips are appreciated. 
I'll post a solution here for future ref. if I get something decent working.

Thanks.

**Comment by henrythasler** [comment]
I was using my [multiline-nosplit](https://blog.cyclemap.link/Leaflet.Geodesic/multiline-nosplit.html) example and just changed line 101 into:
```
var marker = L.marker(place, { draggable: true }).addTo(map).bindTooltip("Works!", {permanent: true, direction: "top", interactive: true, offset: [0, 0]});
```
to show the tooltips. Nothing else.

**Comment by beebase** [comment]
I think this only works if you are drawing a continues line with markers.
When painting separate lines like in my screenshot, I couldn't get it to work with the example code from multiline-nosplit.

Is there a way to get the start/end coordinates of a geodesic object?
I could then just loop through each object and add the markers.
