### ISSUE TITLE
Error when identical coordinates are given to create a geodesic MultiPolyline

### ISSUE THREAD

**Issue by andrewharvey** [henrythasler/Leaflet.Geodesic#9]
If you try to create a geodesic MultiPolyline from point A to point B where A and B are at the same location, the library has an error. I know it's silly to create such a line, but perhaps the library should just silently ignore this rather than error (which happens due to undefined.toRadians()).

**Comment by henrythasler** [comment]
That's right. I'll check it. Thanks for reporting.
